### ISSUE TITLE
Build once, run multiple tests

### ISSUE THREAD

**Issue by Gamadril** [Jarcho/test-cdylib#1]
Is it possible to call `test_cdylib::build_current_project()` once per test file and let all the test functions inside that test file use that build?

**Comment by Jarcho** [comment]
You could use [once_cell](https://crates.io/crates/once_cell) to store the result, e.g.
```rust
use once_cell::sync::Lazy;
static LIB_PATH: Lazy<PathBuf> = Lazy::new(|| test_cdylib::build_current_project());
```

**Comment by Gamadril** [comment]
Thanks, that works fine for me. Maybe you could extend your example with it. The usual test case is to have one test suite with many tests inside.
